### ISSUE TITLE
App crashes when selecting any of the options

### ISSUE THREAD

**Issue by farazk86** [khanhlvg/tflite-task-library-demo#2]
Hi,

Thank you for writing this demo app to better help us understand the new task library. 

I downloaded it and ran it locally to better understand what was going on but when I press the "SegmentImage" button, the app crahes with the following messages:

```
I/tflite: Initialized TensorFlow Lite runtime.
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.khanhlvg.taskapidemo, PID: 15915
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/tensorflow/lite/support/image/ColorSpaceType;
        at org.tensorflow.lite.task.vision.segmenter.OutputType$1.createMasksFromBuffer(OutputType.java:74)
        at org.tensorflow.lite.task.vision.segmenter.ImageSegmenter.segment(ImageSegmenter.java:224)
        at org.tensorflow.lite.task.vision.segmenter.ImageSegmenter.segment(ImageSegmenter.java:176)
        at com.khanhlvg.taskapidemo.ImageSegmenterActivity.onCreate(ImageSegmenterActivity.java:42)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.tensorflow.lite.support.image.ColorSpaceType" on path: DexPathList[[zip file "/data/app/com.khanhlvg.taskapidemo-xcvJ-MgWkVTpfJJcN9GaBw==/base.apk"],nativeLibraryDirectories=[/data/app/com.khanhlvg.taskapidemo-xcvJ-MgWkVTpfJJcN9GaBw==/lib/x86, /data/app/com.khanhlvg.taskapidemo-xcvJ-MgWkVTpfJJcN9GaBw==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at org.tensorflow.lite.task.vision.segmenter.OutputType$1.createMasksFromBuffer(OutputType.java:74) 
        at org.tensorflow.lite.task.vision.segmenter.ImageSegmenter.segment(ImageSegmenter.java:224) 
        at org.tensorflow.lite.task.vision.segmenter.ImageSegmenter.segment(ImageSegmenter.java:176) 
        at com.khanhlvg.taskapidemo.ImageSegmenterActivity.onCreate(ImageSegmenterActivity.java:42) 
        at android.app.Activity.performCreate(Activity.java:7802) 
        at android.app.Activity.performCreate(Activity.java:7791) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

**Comment by farazk86** [comment]
So changing the dependency in app ``build.gradle`` to

```
implementation 'org.tensorflow:tensorflow-lite-task-vision:0.1.0'
```

fixed the problem and app works now.
